language: python
python:
  - "3.6"
#  - "2.7"


addons:
  apt:
    packages:
    - gfortran
env:

  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so

before_install:
  - python --version
  - mkdir tmp
  - cd tmp

install: 
  -  pip install tox-travis -r ../requirements.txt 

before_script:
  cd ..

script:
  - python setup.py install 
  - tox

notifications:
  email: false
