language: python
python:
  - "2.7"
  - "3.6"


addons:
  apt:
    packages:
    - gfortran
env:

  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so

before_install:
- python --version

install: 
  pip install tox-travis setuptools>=30.3.0 future>=0.16 numpy>=1.14 matplotlib scipy>=0.9 toolz>=0.8 dask pandas>=0.20 apexpy>=1.0

script: tox

notifications:
  email: false
