version: '{branch}-{build}'
build: off
configuration: Release
environment:

  matrix:
    - TESTENV: 'py27-64'
      PYTHON_VERSION: '2.7'
      PYTHON: "C:\\Miniconda27-x64"

    - TESTENV: 'py27-32'
      PYTHON_VERSION: '2.7'
      PYTHON: "C:\\Miniconda27"

    - TESTENV: 'py35-64'
      PYTHON_VERSION: '3.5'
      PYTHON: "C:\\Miniconda35-x64"

    - TESTENV: 'py35-32'
      PYTHON_VERSION: '3.5'
      PYTHON: "C:\\Miniconda35"

    - TESTENV: 'py36-64'
      PYTHON_VERSION: '3.6'
      PYTHON: "C:\\Miniconda36-x64"

    - TESTENV: 'py36-32'
      PYTHON_VERSION: '3.6'
      PYTHON: "C:\\Miniconda36"


#init:
install:

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - 'pip install --disable-pip-version-check --user --upgrade pip'

  - 'pip install -r requirements.txt'
  - 'pip install pytest'

test_script:
  - 'pytest tests/ --skip_apex'


