version: '{branch}-{build}'
build: off
configuration: Release
environment:

  matrix:
    - TESTENV: 'py27-64'
      PYTHON_VERSION: '2.7'
      PYTHON: "C:\\Miniconda27-x64"

    - TESTENV: 'py27-32'
      PYTHON_VERSION: '2.7'
      PYTHON: "C:\\Miniconda27"


#init:
install:

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  #- 'pip install --disable-pip-version-check --user --upgrade pip'
  - 'python -m pip install --upgrade pip'   

  - 'pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy'
  - 'pip install numpy>=1.14'
  - 'pip install -r requirements.txt'
  - 'pip install -q -e .'
  - 'pip install pytest'

test_script:
  - 'pytest tests/ --skip_apex'


